name: 'Simply Cakes,etc...Bakery'
favicon: null
layout_spectrum: 0.39767893264070153
typography_spectrum: 0.9485013512894511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8015486178919673
  lightness: 0.8814358324743807
  saturation: 0.48333059693686664
  rhythmicContrast: 0.9912917611654848
purpose: []
